
---
- name: Install HTTP server
  hosts: g1
  become: yes

  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present
    when: ansible_distribution == "Amazon" or ansible_distribution == "CentOS"

  - name: start Httpd
    service:
      name: httpd
      state: started
      enabled: yes


- name: Update n1 servers
  hosts: n1
  
  tasks:
  - name: Create Directory
    file:
      path: /home/ec2-user/new_dir1
      state: directory

  - name: Create Directory
    file:
      path: /home/ec2-user/new_dir2
      state: directory

- name: Update n1 servers
  hosts: n2
  
  tasks:
  - name: Create Directory
    file:
      path: /home/ec2-user/new_dir1
      state: directory

  - name: Create Directory
    file:
      path: /home/ec2-user/new_dir2
      state: directory

- name: Update group1 servers
  hosts: g2
  
  tasks:
  - name: Create Directory
    file:
      path: /home/ec2-user/new_dir_group1
      state: directory

  - name: Create Directory
    file:
      path: /home/ec2-user/new_dir_group2
      state: directory
...
